// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateCountry(ctx context.Context, countryCode string) (int64, error)
	CreateOrUpdateCountry(ctx context.Context, countryCode string) (int64, error)
	CreateOrUpdateProduct(ctx context.Context, arg CreateOrUpdateProductParams) (int64, error)
	CreateOrUpdateStock(ctx context.Context, arg CreateOrUpdateStockParams) (int64, error)
	CreateStock(ctx context.Context, arg CreateStockParams) (CreateStockRow, error)
	GetCountryForUpdate(ctx context.Context, countryCode string) (Country, error)
	GetProductForUpdate(ctx context.Context, sku string) (Product, error)
	GetStockByProductAndCountryeForUpdate(ctx context.Context, arg GetStockByProductAndCountryeForUpdateParams) (GetStockByProductAndCountryeForUpdateRow, error)
	UpdateCountry(ctx context.Context, arg UpdateCountryParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateStock(ctx context.Context, arg UpdateStockParams) error
}

var _ Querier = (*Queries)(nil)
